const follower = {
	login: 'smilga',
	id: 16165581,
	node_id: 'MDQ6VXNlcjE2MTY1NTgx',
	avatar_url: 'https://avatars.githubusercontent.com/u/16165581?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/smilga',
	html_url: 'https://github.com/smilga',
	followers_url: 'https://api.github.com/users/smilga/followers',
	following_url: 'https://api.github.com/users/smilga/following{/other_user}',
	gists_url: 'https://api.github.com/users/smilga/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/smilga/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/smilga/subscriptions',
	organizations_url: 'https://api.github.com/users/smilga/orgs',
	repos_url: 'https://api.github.com/users/smilga/repos',
	events_url: 'https://api.github.com/users/smilga/events{/privacy}',
	received_events_url: 'https://api.github.com/users/smilga/received_events',
	type: 'User',
	site_admin: false,
	name: 'Kaspars',
	company: null,
	blog: '',
	location: 'Latvia',
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 21,
	public_gists: 3,
	followers: 2,
	following: 4,
	created_at: '2015-12-05T12:47:24Z',
	updated_at: '2023-07-02T15:17:23Z'
}
export default follower
